---
kind: pipeline
type: docker
name: default

steps:
  - name: validate
    image: hashicorp/packer:light
    commands:
      - apk -U add ansible
      - packer validate d4-packer/*.json

  - name: terraform plan and apply
    image: hashicorp/terraform:light
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    commands:
      - terraform init -var "hash_commit=$DRONE_COMMIT" ./terraform/
      - terraform plan -var "hash_commit=$DRONE_COMMIT" -out build_plan ./terraform/
      - terraform apply build_plan

  - name: build cluster
    image: hashicorp/packer:light
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      VPC_ID:
        from_secret: VPC_ID
      SUBNET_ID:
        from_secret: SUBNET_ID
      K8S_MASTER_NODE_IP:
        from_secret: K8S_MASTER_NODE_IP
      K8S_API_SECURE_PORT:
        from_secret: K8S_API_SECURE_PORT
    commands:
      - apk -U add ansible
      - packer validate d4-packer/*.json
