- name: Installing Docker
  shell: curl -fsSL https://get.docker.com | bash -

- name: Add K8s apt keys
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding k8s repo
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install k8s packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl
